name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-broker:
    name: Build PostgreSQL
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PostgreSQL
        uses: ./
